Neos:
  Fusion:
    defaultContext:
      StaticPages.Loader: 'Wysiwyg\StaticPages\Eel\Helper\StaticPageLoaderHelper'
  Neos:
    fusion:
      autoInclude:
        Wysiwyg.StaticPages: true

Wysiwyg:
  StaticPages:
    rootFolder: '%FLOW_PATH_ROOT%'
    contentSelector: 'main'
    pageGroups:
      default: []
